# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sorting.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsorting.proto\x12\x07sorting\")\n\x05\x45rror\x12\x0f\n\x07isError\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"P\n\x0eRequestSorting\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\r\n\x05\x61rray\x18\x02 \x03(\x03\x12\x0e\n\x06isDone\x18\x03 \x01(\x08\x12\x11\n\tsleepTime\x18\x04 \x01(\x02\"l\n\x0fResponseSorting\x12\r\n\x05\x61rray\x18\x01 \x03(\x03\x12\x0e\n\x06isDone\x18\x02 \x01(\x08\x12\x0c\n\x04left\x18\x03 \x01(\x03\x12\r\n\x05right\x18\x04 \x01(\x03\x12\x1d\n\x05\x65rror\x18\x05 \x01(\x0b\x32\x0e.sorting.Error2M\n\x0eSortingService\x12;\n\x04Sort\x12\x17.sorting.RequestSorting\x1a\x18.sorting.ResponseSorting0\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sorting_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ERROR._serialized_start=26
  _ERROR._serialized_end=67
  _REQUESTSORTING._serialized_start=69
  _REQUESTSORTING._serialized_end=149
  _RESPONSESORTING._serialized_start=151
  _RESPONSESORTING._serialized_end=259
  _SORTINGSERVICE._serialized_start=261
  _SORTINGSERVICE._serialized_end=338
# @@protoc_insertion_point(module_scope)
