# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proto.sorting_pb2 as sorting__pb2


class SortingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Sort = channel.unary_stream(
                '/sorting.SortingService/Sort',
                request_serializer=sorting__pb2.RequestSorting.SerializeToString,
                response_deserializer=sorting__pb2.ResponseSorting.FromString,
                )


class SortingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Sort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SortingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Sort': grpc.unary_stream_rpc_method_handler(
                    servicer.Sort,
                    request_deserializer=sorting__pb2.RequestSorting.FromString,
                    response_serializer=sorting__pb2.ResponseSorting.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sorting.SortingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SortingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Sort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/sorting.SortingService/Sort',
            sorting__pb2.RequestSorting.SerializeToString,
            sorting__pb2.ResponseSorting.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
