// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: sorting.proto

package sorting

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsError bool   `protobuf:"varint,1,opt,name=isError,proto3" json:"isError,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sorting_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_sorting_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_sorting_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RequestSorting struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      string  `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Array     []int64 `protobuf:"varint,2,rep,packed,name=array,proto3" json:"array,omitempty"`
	IsDone    bool    `protobuf:"varint,3,opt,name=isDone,proto3" json:"isDone,omitempty"`
	SleepTime float32 `protobuf:"fixed32,4,opt,name=sleepTime,proto3" json:"sleepTime,omitempty"`
}

func (x *RequestSorting) Reset() {
	*x = RequestSorting{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sorting_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestSorting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestSorting) ProtoMessage() {}

func (x *RequestSorting) ProtoReflect() protoreflect.Message {
	mi := &file_sorting_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestSorting.ProtoReflect.Descriptor instead.
func (*RequestSorting) Descriptor() ([]byte, []int) {
	return file_sorting_proto_rawDescGZIP(), []int{1}
}

func (x *RequestSorting) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RequestSorting) GetArray() []int64 {
	if x != nil {
		return x.Array
	}
	return nil
}

func (x *RequestSorting) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

func (x *RequestSorting) GetSleepTime() float32 {
	if x != nil {
		return x.SleepTime
	}
	return 0
}

type ResponseSorting struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Array  []int64 `protobuf:"varint,1,rep,packed,name=array,proto3" json:"array,omitempty"`
	IsDone bool    `protobuf:"varint,2,opt,name=isDone,proto3" json:"isDone,omitempty"`
	Left   int64   `protobuf:"varint,3,opt,name=left,proto3" json:"left,omitempty"`
	Right  int64   `protobuf:"varint,4,opt,name=right,proto3" json:"right,omitempty"`
	Error  *Error  `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ResponseSorting) Reset() {
	*x = ResponseSorting{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sorting_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseSorting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseSorting) ProtoMessage() {}

func (x *ResponseSorting) ProtoReflect() protoreflect.Message {
	mi := &file_sorting_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseSorting.ProtoReflect.Descriptor instead.
func (*ResponseSorting) Descriptor() ([]byte, []int) {
	return file_sorting_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseSorting) GetArray() []int64 {
	if x != nil {
		return x.Array
	}
	return nil
}

func (x *ResponseSorting) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

func (x *ResponseSorting) GetLeft() int64 {
	if x != nil {
		return x.Left
	}
	return 0
}

func (x *ResponseSorting) GetRight() int64 {
	if x != nil {
		return x.Right
	}
	return 0
}

func (x *ResponseSorting) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_sorting_proto protoreflect.FileDescriptor

var file_sorting_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x6f, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x73, 0x6f, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x22, 0x3b, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x70, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x53, 0x6f, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61,
	0x72, 0x72, 0x61, 0x79, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x05, 0x61, 0x72, 0x72, 0x61,
	0x79, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x73, 0x44, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x69, 0x73, 0x44, 0x6f, 0x6e, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x6c, 0x65,
	0x65, 0x70, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x73, 0x6c,
	0x65, 0x65, 0x70, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x8f, 0x01, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x53, 0x6f, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x61,
	0x72, 0x72, 0x61, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x05, 0x61, 0x72, 0x72, 0x61,
	0x79, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x73, 0x44, 0x6f, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x69, 0x73, 0x44, 0x6f, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x65, 0x66,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x72, 0x69, 0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x72, 0x69,
	0x67, 0x68, 0x74, 0x12, 0x24, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x6f, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x32, 0x4d, 0x0a, 0x0e, 0x53, 0x6f, 0x72,
	0x74, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x04, 0x53,
	0x6f, 0x72, 0x74, 0x12, 0x17, 0x2e, 0x73, 0x6f, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x6f, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x1a, 0x18, 0x2e, 0x73,
	0x6f, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53,
	0x6f, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x30, 0x01, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x73, 0x6f,
	0x72, 0x74, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sorting_proto_rawDescOnce sync.Once
	file_sorting_proto_rawDescData = file_sorting_proto_rawDesc
)

func file_sorting_proto_rawDescGZIP() []byte {
	file_sorting_proto_rawDescOnce.Do(func() {
		file_sorting_proto_rawDescData = protoimpl.X.CompressGZIP(file_sorting_proto_rawDescData)
	})
	return file_sorting_proto_rawDescData
}

var file_sorting_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sorting_proto_goTypes = []interface{}{
	(*Error)(nil),           // 0: sorting.Error
	(*RequestSorting)(nil),  // 1: sorting.RequestSorting
	(*ResponseSorting)(nil), // 2: sorting.ResponseSorting
}
var file_sorting_proto_depIdxs = []int32{
	0, // 0: sorting.ResponseSorting.error:type_name -> sorting.Error
	1, // 1: sorting.SortingService.Sort:input_type -> sorting.RequestSorting
	2, // 2: sorting.SortingService.Sort:output_type -> sorting.ResponseSorting
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sorting_proto_init() }
func file_sorting_proto_init() {
	if File_sorting_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sorting_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sorting_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestSorting); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sorting_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseSorting); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sorting_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sorting_proto_goTypes,
		DependencyIndexes: file_sorting_proto_depIdxs,
		MessageInfos:      file_sorting_proto_msgTypes,
	}.Build()
	File_sorting_proto = out.File
	file_sorting_proto_rawDesc = nil
	file_sorting_proto_goTypes = nil
	file_sorting_proto_depIdxs = nil
}
